<?php

declare(strict_types=1);

namespace App\Service;

class CommandReferenceGenerator
{
    public const OUTPUT_PATH = 'documentation/reference/commands.md';

    /** @var array<string, string> */
    private const CATEGORY_LABELS = [
        'configuration' => 'Configuration',
        'jira' => 'Jira Work Items',
        'git' => 'Git Workflow',
        'pull-requests' => 'Pull Requests',
        'confluence' => 'Confluence',
        'documentation' => 'Documentation',
        'system' => 'System and Release',
    ];

    public function __construct(
        private readonly TranslationService $translator,
        private readonly CommandReferenceExampleBuilder $exampleBuilder = new CommandReferenceExampleBuilder()
    ) {
    }

    /**
     * Generate the Markdown command reference from the runtime agent schema.
     *
     * @param array{commands: list<array<string, mixed>>} $schema
     */
    public function generate(array $schema): string
    {
        $commands = $this->groupCommands($schema['commands']);
        $lines = $this->buildHeader();
        $lines = array_merge($lines, $this->buildTableOfContents($commands));

        foreach ($commands as $category => $categoryCommands) {
            $lines[] = '';
            $lines[] = '## ' . self::CATEGORY_LABELS[$category];
            foreach ($categoryCommands as $command) {
                $lines = array_merge($lines, $this->buildCommandSection($command));
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Write the generated reference to the repository documentation path.
     *
     * @param array{commands: list<array<string, mixed>>} $schema
     */
    public function write(FileSystem $fileSystem, array $schema): void
    {
        $fileSystem->mkdir(dirname(self::OUTPUT_PATH), recursive: true);
        $fileSystem->write(self::OUTPUT_PATH, $this->generate($schema));
    }

    /**
     * Return true when the checked-in reference matches the generated output.
     *
     * @param array{commands: list<array<string, mixed>>} $schema
     */
    public function isCurrent(FileSystem $fileSystem, array $schema): bool
    {
        try {
            $existing = $fileSystem->read(self::OUTPUT_PATH);
        } catch (\RuntimeException) {
            return false;
        }

        return $existing === $this->generate($schema);
    }

    /**
     * @return list<string>
     */
    protected function buildHeader(): array
    {
        return [
            '# Command Reference',
            '',
            '<!-- This file is generated by `stud docs:generate`. Do not edit it manually. -->',
            '',
            'This reference is generated from the same runtime metadata used by `stud help --agent` and the command help map. It is the exhaustive command/API layer for `stud-cli`.',
        ];
    }

    /**
     * @param array<string, list<array<string, mixed>>> $commands
     *
     * @return list<string>
     */
    protected function buildTableOfContents(array $commands): array
    {
        $lines = ['', '## Contents'];
        foreach ($commands as $category => $categoryCommands) {
            $lines[] = '';
            $lines[] = '### ' . self::CATEGORY_LABELS[$category];
            foreach ($categoryCommands as $command) {
                $name = $this->commandName($command);
                $lines[] = '- [`stud ' . $name . '`](#' . $this->anchorFor($name) . ')';
            }
        }

        return $lines;
    }

    /**
     * @param list<array<string, mixed>> $commands
     *
     * @return array<string, list<array<string, mixed>>>
     */
    protected function groupCommands(array $commands): array
    {
        $grouped = array_fill_keys(array_keys(self::CATEGORY_LABELS), []);
        foreach ($commands as $command) {
            $grouped[$this->categoryFor($this->commandName($command))][] = $command;
        }

        return array_filter($grouped);
    }

    protected function categoryFor(string $name): string
    {
        if (str_starts_with($name, 'config:')) {
            return 'configuration';
        }
        if (str_starts_with($name, 'items:') || str_starts_with($name, 'filters:') || $name === 'projects:list') {
            return 'jira';
        }
        if (in_array($name, ['commit', 'commit:undo', 'push', 'please', 'flatten', 'sync', 'switch', 'status', 'branch:rename', 'branches:list', 'branches:clean'], true)) {
            return 'git';
        }
        if (str_starts_with($name, 'pr:') || $name === 'submit') {
            return 'pull-requests';
        }
        if (str_starts_with($name, 'confluence:')) {
            return 'confluence';
        }
        if (str_starts_with($name, 'docs:')) {
            return 'documentation';
        }

        return 'system';
    }

    /**
     * @param array<string, mixed> $command
     *
     * @return list<string>
     */
    protected function buildCommandSection(array $command): array
    {
        $name = $this->commandName($command);
        $meta = CommandMap::all()[$name] ?? null;
        $aliases = $this->aliases($command);
        $lines = [
            '',
            '<a id="' . $this->anchorFor($name) . '"></a>',
            '### `stud ' . $name . '`',
            '',
            $this->descriptionFor($command, $meta),
            '',
            '- **Alias:** ' . ($aliases === [] ? 'None' : implode(', ', array_map(fn (string $alias): string => '`stud ' . $alias . '`', $aliases))),
            '- **Syntax:** `' . $this->syntaxFor($name, $meta) . '`',
        ];

        $lines = array_merge($lines, $this->buildDetails($name, $command, $meta));

        return $lines;
    }

    /**
     * @param array<string, mixed> $command
     * @param array{alias: ?string, description_key: string, options: array<int, array{name: string, shortcut: ?string, description_key: string, argument: ?string}>, arguments: array<int, string>}|null $meta
     *
     * @return list<string>
     */
    protected function buildDetails(string $name, array $command, ?array $meta): array
    {
        $lines = ['', '<details>', '<summary>Options, examples, and agent schema</summary>', ''];
        $lines = array_merge($lines, $this->buildArguments($meta));
        $lines = array_merge($lines, $this->buildOptions($meta, $command));
        $lines = array_merge($lines, $this->exampleBuilder->build($name, $command, $meta, $this->aliases($command)));
        $lines = array_merge($lines, $this->buildAgentInput($command));
        $lines = array_merge($lines, $this->buildAgentOutput($command));
        $lines[] = '</details>';

        return $lines;
    }

    /**
     * @param array{arguments: array<int, string>}|null $meta
     *
     * @return list<string>
     */
    protected function buildArguments(?array $meta): array
    {
        $arguments = $meta['arguments'] ?? [];
        if ($arguments === []) {
            return ['#### Arguments', '', 'None.', ''];
        }

        $lines = ['#### Arguments', '', '| Argument |', '| --- |'];
        foreach ($arguments as $argument) {
            $lines[] = '| `' . $this->escapeTable($argument) . '` |';
        }
        $lines[] = '';

        return $lines;
    }

    /**
     * @param array{options: array<int, array{name: string, shortcut: ?string, description_key: string, argument: ?string}>}|null $meta
     * @param array<string, mixed> $command
     *
     * @return list<string>
     */
    protected function buildOptions(?array $meta, array $command): array
    {
        $options = $meta['options'] ?? [];
        if ($options === []) {
            $schemaOptions = $command['parameters']['options'] ?? [];
            if (! is_array($schemaOptions) || $schemaOptions === []) {
                return ['#### Options', '', 'None.', ''];
            }
        }

        $lines = ['#### Options', '', '| Option | Description |', '| --- | --- |'];
        foreach ($options as $option) {
            $signature = $option['name'] . ($option['argument'] !== null ? ' ' . $option['argument'] : '');
            if ($option['shortcut'] !== null) {
                $signature .= '<br>`' . $option['shortcut'] . ($option['argument'] !== null ? ' ' . $option['argument'] : '') . '`';
            }
            $lines[] = '| `' . $this->escapeTable($signature) . '` | ' . $this->escapeTable($this->translator->trans($option['description_key'])) . ' |';
        }
        if ($options === []) {
            foreach ($command['parameters']['options'] as $option) {
                $lines[] = '| `' . $this->escapeTable((string) $option) . '` | See command schema. |';
            }
        }
        $lines[] = '';

        return $lines;
    }

    /**
     * @param array<string, mixed> $command
     *
     * @return list<string>
     */
    protected function buildAgentInput(array $command): array
    {
        $properties = $command['input']['properties'] ?? [];
        if (! is_array($properties) || $properties === []) {
            return ['#### Agent JSON Input', '', 'No input properties.', ''];
        }

        $lines = ['#### Agent JSON Input', '', '| Property | Type | Optional | Default |', '| --- | --- | --- | --- |'];
        foreach ($properties as $property => $schema) {
            $schema = is_array($schema) ? $schema : [];
            $lines[] = '| `' . $this->escapeTable((string) $property) . '` | `' . $this->escapeTable((string) ($schema['type'] ?? 'mixed')) . '` | ' . ($schema['optional'] ?? false ? 'yes' : 'no') . ' | `' . $this->escapeTable($this->defaultValue($schema)) . '` |';
        }
        $lines[] = '';

        return $lines;
    }

    /**
     * @param array<string, mixed> $command
     *
     * @return list<string>
     */
    protected function buildAgentOutput(array $command): array
    {
        $output = $command['output'] ?? [];
        if (! is_array($output)) {
            return [];
        }
        $lines = ['#### Agent JSON Output', ''];
        if (isset($output['description']) && is_string($output['description']) && $output['description'] !== '') {
            $lines[] = $output['description'];
            $lines[] = '';
        }
        $lines[] = 'Success data:';
        $lines[] = '';
        $lines[] = '```text';
        $lines[] = $this->renderOutputShape($output['success']['data'] ?? '(undescribed)');
        $lines[] = '```';
        $lines[] = '';
        $lines[] = 'Error shape: `{"success":false,"error":"string"}`';
        $lines[] = '';

        return $lines;
    }

    /**
     * @param mixed $shape
     */
    protected function renderOutputShape(mixed $shape): string
    {
        if (! is_array($shape)) {
            return (string) $shape;
        }

        $lines = [];
        foreach ($shape as $key => $type) {
            $lines[] = $key . ': ' . (is_array($type) ? 'array' : (string) $type);
        }

        return implode("\n", $lines);
    }

    /**
     * @param array<string, mixed> $command
     */
    protected function commandName(array $command): string
    {
        return (string) $command['name'];
    }

    /**
     * @param array<string, mixed> $command
     *
     * @return list<string>
     */
    protected function aliases(array $command): array
    {
        $aliases = $command['aliases'] ?? [];

        return is_array($aliases) ? array_values(array_filter($aliases, 'is_string')) : [];
    }

    /**
     * @param array<string, mixed> $command
     * @param array{description_key: string}|null $meta
     */
    protected function descriptionFor(array $command, ?array $meta): string
    {
        if ($meta !== null) {
            return $this->translator->trans($meta['description_key']);
        }

        return (string) ($command['description'] ?? 'No description available.');
    }

    /**
     * @param array{options: array<int, mixed>, arguments: array<int, string>}|null $meta
     */
    protected function syntaxFor(string $name, ?array $meta): string
    {
        $parts = ['stud', $name];
        foreach ($meta['arguments'] ?? [] as $argument) {
            $parts[] = $argument;
        }
        if (($meta['options'] ?? []) !== []) {
            $parts[] = '[options]';
        }

        return implode(' ', $parts);
    }

    protected function anchorFor(string $name): string
    {
        return 'stud-' . str_replace(':', '-', $name);
    }

    /**
     * @param array<string, mixed> $schema
     */
    protected function defaultValue(array $schema): string
    {
        if (! array_key_exists('default', $schema)) {
            return '';
        }

        if (is_scalar($schema['default']) || $schema['default'] === null) {
            return var_export($schema['default'], true);
        }

        $encoded = json_encode($schema['default'], JSON_UNESCAPED_SLASHES);

        return is_string($encoded) ? $encoded : '';
    }

    protected function escapeTable(string $value): string
    {
        return str_replace('|', '\\|', $value);
    }
}
