<?php

declare(strict_types=1);

namespace App\Tests\Service;

use App\Service\CommandReferenceExampleBuilder;
use App\Service\CommandReferenceGenerator;
use App\Service\FileSystem;
use App\Service\TranslationService;
use League\Flysystem\Filesystem as FlysystemFilesystem;
use League\Flysystem\InMemory\InMemoryFilesystemAdapter;
use PHPUnit\Framework\TestCase;

class CommandReferenceGeneratorTest extends TestCase
{
    private CommandReferenceGenerator $generator;
    private FileSystem $fileSystem;

    protected function setUp(): void
    {
        parent::setUp();

        $translator = $this->createMock(TranslationService::class);
        $translator->method('trans')->willReturnCallback(
            fn (string $key): string => 'translated:' . $key
        );

        $this->generator = new CommandReferenceGenerator($translator);
        $this->fileSystem = new FileSystem(new FlysystemFilesystem(new InMemoryFilesystemAdapter()));
    }

    public function testGenerateBuildsReferenceWithTocDetailsAndAgentSchema(): void
    {
        $markdown = $this->generator->generate($this->schema());

        $this->assertStringContainsString('# Command Reference', $markdown);
        $this->assertStringContainsString('[`stud config:validate`](#stud-config-validate)', $markdown);
        $this->assertStringContainsString('<details>', $markdown);
        $this->assertStringContainsString('translated:help.command_config_validate', $markdown);
        $this->assertStringContainsString('`--skip-jira`', $markdown);
        $this->assertStringContainsString('echo \'{"skipJira":true}\' | stud config:validate --agent', $markdown);
        $this->assertStringNotContainsString('echo \'{"compact":true', $markdown);
        $this->assertStringContainsString('success: true', $markdown);
        $this->assertStringContainsString('jira: bool', $markdown);
        $this->assertStringContainsString('Default compact success shape (`{"compact":true}` or omitted):', $markdown);
        $this->assertStringContainsString('Full success shape (`{"compact":false}`):', $markdown);
    }

    public function testWriteCreatesExpectedFileAndIsCurrentChecksExactContent(): void
    {
        $schema = $this->schema();

        $this->assertFalse($this->generator->isCurrent($this->fileSystem, $schema));

        $this->generator->write($this->fileSystem, $schema);

        $this->assertTrue($this->generator->isCurrent($this->fileSystem, $schema));
        $this->assertStringContainsString(
            '<!-- This file is generated by `stud docs:generate`. Do not edit it manually. -->',
            $this->fileSystem->read(CommandReferenceGenerator::OUTPUT_PATH)
        );
    }

    public function testCheckDetectsStaleContent(): void
    {
        $this->fileSystem->mkdir('documentation/reference', recursive: true);
        $this->fileSystem->write(CommandReferenceGenerator::OUTPUT_PATH, 'stale');

        $this->assertFalse($this->generator->isCurrent($this->fileSystem, $this->schema()));
    }

    public function testGenerateHandlesUnmappedCommandsAndSchemaOnlyOptions(): void
    {
        $markdown = $this->generator->generate([
            'commands' => [
                [
                    'name' => 'custom:tool',
                    'aliases' => ['ct'],
                    'description' => 'Custom command',
                    'parameters' => [
                        'options' => ['custom-option'],
                        'arguments' => [],
                    ],
                    'input' => ['properties' => []],
                    'output' => 'unexpected',
                ],
            ],
        ]);

        $this->assertStringContainsString('## System and Release', $markdown);
        $this->assertStringContainsString('Custom command', $markdown);
        $this->assertStringContainsString('| `custom-option` | See command schema. |', $markdown);
        $this->assertStringContainsString('echo \'{}\' | stud custom:tool --agent', $markdown);
        $this->assertStringNotContainsString('#### Agent JSON Output', $markdown);
    }

    public function testExampleBuilderSamplesCommonArgumentAndPropertyValues(): void
    {
        $builder = new TestableCommandReferenceExampleBuilder();

        foreach ($this->argumentSamples() as $argument => $expected) {
            $this->assertSame($expected, $builder->argumentSample($argument));
        }

        foreach ($this->propertySamples() as $property => $expected) {
            $this->assertSame($expected, $builder->propertySample($property, ['type' => 'string']));
        }

        $this->assertTrue($builder->propertySample('quiet', ['type' => 'bool']));
        $this->assertSame(1, $builder->propertySample('transitionId', ['type' => 'int|null']));
        $this->assertSame(['example'], $builder->propertySample('files', ['type' => 'array']));
    }

    public function testGenerateCoversArgumentsOptionArgumentsAndAllCategories(): void
    {
        $markdown = $this->generator->generate([
            'commands' => [
                $this->command('items:show', ['arguments' => ['<key>']]),
                $this->command('branch:rename'),
                $this->command('switch', ['arguments' => ['<key>']]),
                $this->command('submit'),
                $this->command('confluence:show'),
                $this->command('docs:check'),
                $this->command('release', ['outputData' => 'message']),
            ],
        ]);

        $this->assertStringContainsString('| `<key>` |', $markdown);
        $this->assertStringContainsString('## Jira Work Items', $markdown);
        $this->assertStringContainsString('## Git Workflow', $markdown);
        $this->assertStringContainsString('[`stud switch`](#stud-switch)', $markdown);
        $this->assertStringContainsString('## Pull Requests', $markdown);
        $this->assertStringContainsString('## Confluence', $markdown);
        $this->assertStringContainsString('## Documentation', $markdown);
        $this->assertStringContainsString('## System and Release', $markdown);
        $this->assertStringContainsString('```text' . "\nsuccess: true\nmessage\n" . '```', $markdown);
    }

    public function testProtectedRenderingHelpersCoverEdgeCases(): void
    {
        $generator = new TestableCommandReferenceGenerator($this->translator());

        $this->assertSame(['#### Options', '', 'None.', ''], $generator->options(null, [
            'parameters' => ['options' => []],
        ]));
        $this->assertSame('rows: array', $generator->outputShape(['rows' => ['nested']]));
        $this->assertSame('(undescribed)', $generator->payloadShape('(undescribed)'));
        $this->assertSame('success: true', $generator->payloadShape(['success' => true]));
        $this->assertSame('', $generator->defaultValueFor([]));
        $this->assertSame('', $generator->defaultValueFor(['default' => fopen('php://memory', 'r')]));
    }

    /**
     * @return array<string, string>
     */
    private function argumentSamples(): array
    {
        return [
            '<key>' => 'SCI-123',
            '<jql>' => '"project = SCI and statusCategory != Done"',
            '<filterName>' => '"My Filter"',
            '<shell>' => 'bash',
            '<message>' => '"Ready for review"',
            '<version>' => '1.2.0',
            '<branch>' => 'feat/SCI-123-existing-branch',
            '<name>' => 'custom-branch-name',
            '<type>' => 'Task',
            '<text>' => '"Updated text"',
            '<plain|markdown>' => 'markdown',
            '<fields>' => '"labels=DX;priority=High"',
            '<path>' => 'doc.md',
            '<dir>' => '.cursor/tmp/SCI-123',
            '<url>' => '"https://example.atlassian.net/wiki/spaces/DEV/pages/12345/Page"',
            '<id>' => '12345',
            '<title>' => '"Feature documentation"',
            '<email>' => 'user@example.com',
            '<list>' => 'research,DX',
            '<labels>' => '"AI-Generated,RFR"',
            '<target>' => 'github:review_thread:THREAD_ID',
            '<unknown>' => 'unknown',
        ];
    }

    /**
     * @return array<string, string>
     */
    private function propertySamples(): array
    {
        return [
            'key' => 'SCI-123',
            'issueKey' => 'SCI-123',
            'commandName' => 'config:validate',
            'command' => 'config:validate',
            'jql' => 'project = SCI and statusCategory != Done',
            'filterName' => 'My Filter',
            'message' => 'Ready for review',
            'labels' => 'AI-Generated,RFR',
            'fields' => 'labels=DX;priority=High',
            'url' => 'https://example.atlassian.net/wiki/spaces/DEV/pages/12345/Page',
            'file' => 'doc.md',
            'content' => '# Feature documentation',
            'page' => '12345',
            'pageId' => '12345',
            'title' => 'Feature documentation',
            'space' => 'DEV',
            'projectKey' => 'SCI',
            'baseBranch' => 'develop',
            'other' => 'example',
        ];
    }

    /**
     * @return array{commands: list<array<string, mixed>>}
     */
    private function schema(): array
    {
        return [
            'commands' => [
                [
                    'name' => 'config:validate',
                    'aliases' => [],
                    'description' => 'Validate configuration',
                    'parameters' => [
                        'options' => ['skip-jira'],
                        'arguments' => [],
                    ],
                    'input' => [
                        'properties' => [
                            'compact' => [
                                'type' => 'bool',
                                'optional' => true,
                                'default' => true,
                            ],
                            'skipJira' => [
                                'type' => 'bool',
                                'optional' => true,
                                'default' => false,
                            ],
                        ],
                    ],
                    'output' => [
                        'description' => 'Connectivity status',
                        'success' => [
                            'success' => true,
                            'data' => [
                                'jira' => 'bool',
                                'git' => 'bool',
                            ],
                        ],
                        'compactSuccess' => [
                            'success' => true,
                            'data' => [
                                'jira' => 'bool',
                                'git' => 'bool',
                            ],
                        ],
                        'error' => ['success' => false, 'error' => 'string'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @param array{arguments?: list<string>, outputData?: mixed} $overrides
     *
     * @return array<string, mixed>
     */
    private function command(string $name, array $overrides = []): array
    {
        return [
            'name' => $name,
            'aliases' => [],
            'description' => 'Description for ' . $name,
            'parameters' => [
                'options' => [],
                'arguments' => $overrides['arguments'] ?? [],
            ],
            'input' => [
                'properties' => [],
            ],
            'output' => [
                'description' => null,
                'success' => [
                    'success' => true,
                    'data' => $overrides['outputData'] ?? ['message' => 'string'],
                ],
                'compactSuccess' => $overrides['compactOutput'] ?? [
                    'success' => true,
                    'data' => $overrides['outputData'] ?? ['message' => 'string'],
                ],
                'error' => ['success' => false, 'error' => 'string'],
            ],
        ];
    }

    private function translator(): TranslationService
    {
        $translator = $this->createMock(TranslationService::class);
        $translator->method('trans')->willReturnArgument(0);

        return $translator;
    }
}

class TestableCommandReferenceExampleBuilder extends CommandReferenceExampleBuilder
{
    public function argumentSample(string $argument): string
    {
        return $this->sampleForArgument($argument);
    }

    /**
     * @param array<string, mixed> $schema
     */
    public function propertySample(string $property, array $schema): mixed
    {
        return $this->sampleForProperty($property, $schema);
    }
}

class TestableCommandReferenceGenerator extends CommandReferenceGenerator
{
    /**
     * @param array{options: array<int, array{name: string, shortcut: ?string, description_key: string, argument: ?string}>}|null $meta
     * @param array<string, mixed> $command
     *
     * @return list<string>
     */
    public function options(?array $meta, array $command): array
    {
        return $this->buildOptions($meta, $command);
    }

    public function outputShape(mixed $shape): string
    {
        return $this->renderOutputShape($shape);
    }

    public function payloadShape(mixed $shape): string
    {
        return $this->renderPayloadShape($shape);
    }

    /**
     * @param array<string, mixed> $schema
     */
    public function defaultValueFor(array $schema): string
    {
        return $this->defaultValue($schema);
    }
}
