<?php

declare(strict_types=1);

// This file is auto-generated by 'composer dump-config'

return [
    'repo_slug' => 'studapart/stud-cli',
    'description' => 'Stud Cli DX - Jira & Git Workflow Streamliner',
    'version' => '3.4.0',
];
