<?php

// This file is auto-generated by 'composer dump-config'

return  [
  'repo_slug' => 'studapart/stud-cli',
  'description' => 'Stud Cli DX - Jira & Git Workflow Streamliner',
  'version' => '2.6.2',
];
