<?php

$composerJson = json_decode(file_get_contents(__DIR__ . '/../composer.json'), true);

$config = [
    'repo_slug' => $composerJson['name'],
    'description' => $composerJson['description'],
    'version' => $composerJson['version'],
];

$configContent = "<?php\n\ndeclare(strict_types=1);\n\n// This file is auto-generated by 'composer dump-config'\n\nreturn [\n";
foreach ($config as $key => $value) {
    $configContent .= "    '{$key}' => " . var_export($value, true) . ",\n";
}
$configContent .= "];\n";

if (!is_dir(__DIR__ . '/../src/config')) {
    mkdir(__DIR__ . '/../src/config');
}

file_put_contents(__DIR__ . '/../src/config/app.php', $configContent);
