<?php

$composerJson = json_decode(file_get_contents(__DIR__ . '/../composer.json'), true);

$config = [
    'repo_slug' => $composerJson['name'],
    'description' => $composerJson['description'],
    'version' => $composerJson['version'],
];

$configContent = "<?php\n\n// This file is auto-generated by 'composer dump-config'\n\nreturn " . var_export($config, true) . ";\n";

if (!is_dir(__DIR__ . '/../src/config')) {
    mkdir(__DIR__ . '/../src/config');
}

file_put_contents(__DIR__ . '/../src/config/app.php', $configContent);
